<?php

/**
 * BaseSirenaPruebaAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property SirenaPrueba $SirenaPrueba
 * @property JobeetAffiliate $JobeetAffiliate
 * 
 * @method integer               getCategoryId()      Returns the current record's "category_id" value
 * @method integer               getAffiliateId()     Returns the current record's "affiliate_id" value
 * @method SirenaPrueba          getSirenaPrueba()    Returns the current record's "SirenaPrueba" value
 * @method JobeetAffiliate       getJobeetAffiliate() Returns the current record's "JobeetAffiliate" value
 * @method SirenaPruebaAffiliate setCategoryId()      Sets the current record's "category_id" value
 * @method SirenaPruebaAffiliate setAffiliateId()     Sets the current record's "affiliate_id" value
 * @method SirenaPruebaAffiliate setSirenaPrueba()    Sets the current record's "SirenaPrueba" value
 * @method SirenaPruebaAffiliate setJobeetAffiliate() Sets the current record's "JobeetAffiliate" value
 * 
 * @package    sirenaPrueba
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSirenaPruebaAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sirena_prueba_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SirenaPrueba', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('JobeetAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}