<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/18 15:47:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sirenaPrueba',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
