<?php

/**
 * SirenaPruebaAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SirenaPruebaAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SirenaPruebaAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SirenaPruebaAffiliate');
    }
}