<?php

/**
 * SirenaPruebaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SirenaPruebaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SirenaPruebaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SirenaPrueba');
    }
}